import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Card from "@/components/card/card";
import Button, { ButtonWithProps } from "@/components/button/button";
import Alert from "@/components/alert/alert";
import { Box, Stack } from "@ctlyst-test/voila-ui";
import theme from "@/theme/theme.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ backgroundColor: theme.color["green-1"] }}>
        <Card size="medium" />

        <hr></hr>

        <Button>Button 1</Button>
        <br></br>
        <ButtonWithProps
          backgroundColor="blue-1"
          color="red"
          p="3"
          margin="5px"
          py={{
            sm: "2",
          }}
        >
          Button 2
        </ButtonWithProps>

        <hr></hr>
        <Alert rounded color="brand" size="large" />
      </main>
    </>
  );
}
